## Titanic- Who all survived?


### Importing Libraries

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### lmporting the dataset

In [2]:
df=pd.read_csv('train.csv')

### Displaying 5 rows of the dataset

In [3]:
df.head()

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

### Rows and columns

In [4]:
df.shape

(891, 12)

### Information of dataset: Non null values of the dataset

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Pclass       891 non-null    int64  
 2   Name         891 non-null    object 
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
 11  Survived     891 non-null    int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


### Description of columns in the dataset

In [6]:
df.describe()

PassengerId      Pclass         Age       SibSp       Parch  \
count   891.000000  891.000000  714.000000  891.000000  891.000000   
mean    446.000000    2.308642   29.699118    0.523008    0.381594   
std     257.353842    0.836071   14.526497    1.102743    0.806057   
min       1.000000    1.000000    0.420000    0.000000    0.000000   
25%     223.500000    2.000000   20.125000    0.000000    0.000000   
50%     446.000000    3.000000   28.000000    0.000000    0.000000   
75%     668.500000    3.000000   38.000000    1.000000    0.000000   
max     891.000000    3.000000   80.000000    8.000000    6.000000   

             Fare    Survived  
count  891.000000  891.000000  
mean    32.204208    0.383838  
std     49.693429    0.486592  
min      0.000000    0.000000  
25%      7.910400    0.000000  
50%     14.454200    0.000000  
75%     31.000000    1.000000  
max    512.329200    1.000000

### Null values

In [7]:
df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Survived         0
dtype: int64

### Drop column Cabin, Ticket and Name

In [8]:
df=df.drop(['Cabin','Ticket','Name'],axis=1)

In [9]:
df.isnull().sum()

PassengerId      0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         2
Survived         0
dtype: int64

### Drop null values from Embarked

In [10]:
df.dropna(subset=['Embarked'],inplace=True)

### Impute Age 

In [11]:
max(df['Age'])

80.0

In [12]:
min(df['Age'])

0.42

Maximum age is 80 while the minimum is 0.42, all values lie between this range.
I prefer imputing the null values with mean

In [13]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [14]:
df.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
Survived       0
dtype: int64

### Encoding categorical Values

In [15]:
df["Sex"] = df["Sex"].astype('category')
df["Embarked"] = df["Embarked"].astype('category')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   PassengerId  889 non-null    int64   
 1   Pclass       889 non-null    int64   
 2   Sex          889 non-null    category
 3   Age          889 non-null    float64 
 4   SibSp        889 non-null    int64   
 5   Parch        889 non-null    int64   
 6   Fare         889 non-null    float64 
 7   Embarked     889 non-null    category
 8   Survived     889 non-null    int64   
dtypes: category(2), float64(2), int64(5)
memory usage: 57.5 KB


In [17]:
df['Sex'] = df['Sex'].cat.codes
df['Embarked'] = df['Embarked'].cat.codes

In [18]:
df.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0            1       3    1  22.0      1      0   7.2500         2         0
1            2       1    0  38.0      1      0  71.2833         0         1
2            3       3    0  26.0      0      0   7.9250         2         1
3            4       1    0  35.0      1      0  53.1000         2         1
4            5       3    1  35.0      0      0   8.0500         2         0

### Splitting the dataset into input and outcome columns

In [19]:
x = df.drop(["Survived"], axis=1)
y = df["Survived"]

In [20]:
x.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1       3    1  22.0      1      0   7.2500         2
1            2       1    0  38.0      1      0  71.2833         0
2            3       3    0  26.0      0      0   7.9250         2
3            4       1    0  35.0      1      0  53.1000         2
4            5       3    1  35.0      0      0   8.0500         2

### For Standard Scaling of Age and Fare column

In [21]:
"""
col_names = ['Age', 'Fare']
features = x[col_names]
scaler = StandardScaler().fit(features.values)
features = scaler.transform(features.values)
 
x[col_names] = features
x
"""

"\ncol_names = ['Age', 'Fare']\nfeatures = x[col_names]\nscaler = StandardScaler().fit(features.values)\nfeatures = scaler.transform(features.values)\n \nx[col_names] = features\nx\n"

### Applying Logistic Regression Algorithm

In [22]:
from sklearn.linear_model import LogisticRegression
classifier_1 = LogisticRegression(random_state = 0)
classifier_1.fit(x, y)

y_pred = classifier_1.predict(x)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, y_pred)
print(cm)
accuracy_score(y, y_pred)

[[475  74]
 [113 227]]


C:\Users\urvas\anaconda3\envs\virenv\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7896512935883014

### Applying KNN Algorithm

In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier_2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_2.fit(x, y)

y_pred = classifier_2.predict(x)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, y_pred)
print(cm)
accuracy_score(y, y_pred)

[[479  70]
 [149 191]]


0.7536557930258717

### Applying Linear SVC Algorithm

In [24]:
from sklearn.svm import SVC
classifier_3 = SVC(kernel = 'linear', random_state = 0)
classifier_3.fit(x, y)

y_pred = classifier_3.predict(x)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, y_pred)
print(cm)
accuracy_score(y, y_pred)

[[479  70]
 [110 230]]


0.7975253093363329

### Applying Kernel SVC Algorithm

In [25]:
from sklearn.svm import SVC
classifier_4 = SVC(kernel = 'rbf', random_state = 0)
classifier_4.fit(x, y)

y_pred = classifier_4.predict(x)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, y_pred)
print(cm)
accuracy_score(y, y_pred)

[[536  13]
 [284  56]]


0.6659167604049494

### Applying Naive Bayes Algorithm

In [26]:
from sklearn.naive_bayes import GaussianNB
classifier_5 = GaussianNB()
classifier_5.fit(x, y)

y_pred = classifier_5.predict(x)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, y_pred)
print(cm)
accuracy_score(y, y_pred)

[[457  92]
 [ 93 247]]


0.7919010123734533

### Applying Decision Tree Algorithm

In [27]:
from sklearn.tree import DecisionTreeClassifier
classifier_6 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_6.fit(x, y)

y_pred = classifier_6.predict(x)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, y_pred)
print(cm)
accuracy_score(y, y_pred)

[[549   0]
 [  0 340]]


1.0

### Applying Random Forest Algorithm

In [28]:
from sklearn.ensemble import RandomForestClassifier
classifier_7 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_7.fit(x, y)

y_pred = classifier_7.predict(x)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, y_pred)
print(cm)
accuracy_score(y, y_pred)

[[546   3]
 [ 15 325]]


0.9797525309336333

### Importing the test dataset to apply Random Forest Algorithm

In [29]:
df_test = pd.read_csv('test.csv')
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

### Information of columns in the dataset

In [30]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


### Dropping Cabin, Ticket and Name columns of test dataset

In [31]:
df_test = df_test.drop(['Cabin','Ticket','Name'],axis=1)

### Drop null values from Fare column

In [32]:
df_test.dropna(subset=['Fare'],inplace=True)

### Null values in the test dataset

In [33]:
df_test.isnull().sum()

PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            0
Embarked        0
dtype: int64

There are 86 null values in "Age" , I prefer imputing the null values with mean

In [34]:
df_test["Age"] = df_test["Age"].fillna(df_test["Age"].mean())

### Now null values in the dataset

In [35]:
df_test.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

### Converting Sex and embarked column into categories

In [36]:
df_test["Sex"] = df_test["Sex"].astype('category')
df_test["Embarked"] = df_test["Embarked"].astype('category')

df_test['Sex'] = df_test['Sex'].cat.codes
df_test['Embarked'] = df_test['Embarked'].cat.codes

### Now displaying 5 rows of the dataset

In [37]:
df_test.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          892       3    1  34.5      0      0   7.8292         1
1          893       3    0  47.0      1      0   7.0000         2
2          894       2    1  62.0      0      0   9.6875         1
3          895       3    1  27.0      0      0   8.6625         2
4          896       3    0  22.0      1      1  12.2875         2

### Predicting the outcome for the test dataset with Random Forest Classifier

In [38]:
y_pred_1 = classifier_7.predict(df_test)
df_test["Outcome"] = y_pred_1

### Saving the Passenger and outcome in a new dataframe

In [39]:
df_submission = df_test
df_submission = df_submission.drop(['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked'],axis=1)
df_submission.head()

PassengerId  Outcome
0          892        0
1          893        0
2          894        0
3          895        0
4          896        0

### Saving a datast into a new excel file

In [42]:
df_submission.to_excel("Titanic_Submission.xlsx", index=False) # Write DateFrame back as Excel file